-- MySQL Script generated by MySQL Workbench
-- Fri May 11 13:29:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema foro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foro` DEFAULT CHARACTER SET utf8 ;
USE `foro` ;

-- -----------------------------------------------------
-- Table `foro`.`sort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`sort` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '网站文章主类别',
  `name` VARCHAR(45) NOT NULL COMMENT '类别中文名称',
  `url` VARCHAR(45) NOT NULL,
  `order_by` TINYINT NOT NULL DEFAULT 0 COMMENT '排序',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建更新时间',
  `isdel` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foro`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foro`.`content` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(245) NOT NULL COMMENT '文章标题',
  `short_url` VARCHAR(45) NOT NULL COMMENT '短网址',
  `md_text` TEXT NOT NULL,
  `sort` TINYINT UNSIGNED NOT NULL COMMENT '内容类别',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建更新时间',
  `isdel` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `short_url_UNIQUE` (`short_url` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
